"""Publish The Prospect Wire digest to Beehiiv via API."""

import logging
from datetime import date, timedelta

import requests

import config

logger = logging.getLogger(__name__)

BEEHIIV_API_BASE = "https://api.beehiiv.com/v2"


def publish_to_beehiiv(digest_html: str, article_count: int) -> dict:
    if not config.BEEHIIV_API_KEY or not config.BEEHIIV_PUB_ID:
        logger.warning("Beehiiv API key or publication ID not configured. Skipping.")
        return {}

    today = date.today()
    week_start = today - timedelta(days=6)
    title = (
        f"The Prospect Wire - Week of "
        f"{week_start.strftime('%b %d')} to {today.strftime('%b %d, %Y')}"
    )
    subtitle = f"{article_count} prospect stories this week"

    content_parts = [digest_html]
    content_parts.append(
        "<hr><p><em>Generated by The Prospect Wire using Claude AI. "
        "Sources: MLB.com, Baseball America, FanGraphs, D1Baseball, "
        "Perfect Game, Prospects Live, Google News.</em></p>"
    )
    content_html = "\n".join(content_parts)

    url = f"{BEEHIIV_API_BASE}/publications/{config.BEEHIIV_PUB_ID}/posts"
    headers = {
        "Authorization": f"Bearer {config.BEEHIIV_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "title": title,
        "subtitle": subtitle,
        "content_html": content_html,
        "status": "confirmed",
    }

    resp = requests.post(url, json=payload, headers=headers, timeout=60)
    resp.raise_for_status()
    result = resp.json().get("data", {})

    post_id = result.get("id", "unknown")
    post_url = result.get("web_url", "")
    logger.info(f"Beehiiv: published post {post_id} - {post_url}")

    return result
